version: "3.8"
services:
    eureka-discovery:
        build:
            context: ../eureka-discovery
            dockerfile: Dockerfile
        ports:
            - "8761:8761"
    jwt-auth:
        build:
            context: ../jwt-auth
            dockerfile: Dockerfile
        ports:
            - "8800:8800"
    api-gateway:
        build:
            dockerfile: Dockerfile
        ports:
            - "8500:8500"
    example-client:
        build:
            context: ../example-client
            dockerfile: Dockerfile
        ports:
            - "8700:8700"
    ms-product:
        build:
            context: ../ms-product
            dockerfile: Dockerfile
        ports:
            - "8083:8083"
