version: "3.8"
services:
  api-gateway:
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - "8500:8500"
  eurekaserver:
    image: eurekaserver
    build:
      context: eureka-discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"

  processing-postgres:
    image: "postgres:9.6-alpine"
    container_name: processing-postgres
    volumes:
      - processing-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=processing
      - POSTGRES_USER=processing
      - POSTGRES_PASSWORD=processing
    ports:
      - "5432:5432"

  example-client:
    build:
      context: example-client
      dockerfile: Dockerfile
    ports:
      - "8700:8700"
  jwt-auth:
    build:
      context: jwt-auth
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
  ms-user:
    build:
      context: ms-user
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_SERVER=processing-postgres
      - POSTGRES_DB=processing
      - POSTGRES_USER=processing
      - POSTGRES_PASSWORD=processing
    links:
      - processing-postgres
  ms-card:
    build:
      context: ms-card
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_SERVER=processing-postgres
      - POSTGRES_DB=processing
      - POSTGRES_USER=processing
      - POSTGRES_PASSWORD=processing
    links:
      - processing-postgres
  ms-product:
    build:
      context: ms-product
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - DB_SERVER=processing-postgres
      - POSTGRES_DB=processing
      - POSTGRES_USER=processing
      - POSTGRES_PASSWORD=processing
    links:
      - processing-postgres
  ms-payment:
    build:
      context: ms-payment
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - DB_SERVER=processing-postgres
      - POSTGRES_DB=processing
      - POSTGRES_USER=processing
      - POSTGRES_PASSWORD=processing
    links:
      - processing-postgres
volumes:
  processing-data: